CREATE SCHEMA INSTANCE;

CREATE  TABLE "carcrash_dw_lgl".INSTANCE.DIM_CONTRIBUTINGFACTORS ( 
	CONTRIBUTINGFACTOR_ID BIGINT NOT NULL   ,
	CONTRIBUTING_FACTOR  VARCHAR(255)    ,
	CONSTRAINT PK_DIM_CONTRIBUTINGFACTORS PRIMARY KEY ( CONTRIBUTINGFACTOR_ID )
 );

CREATE  TABLE "carcrash_dw_lgl".INSTANCE.DIM_DATE ( 
	DATE_ID              BIGINT NOT NULL   ,
	YEAR                 INT    ,
	MONTHNUMBER          INT    ,
	QUARTER              INT    ,
	DAYNUMBER            INT    ,
	DAYNAME              VARCHAR(50)    ,
	MONTHNAME            VARCHAR(50)    ,
	WEEK_OF_THE_MONTH    INT    ,
	WEEK_OF_THE_YEAR     INT    ,
	HOURNUMBER           INT    ,
	DATE_ISOFORMAT       DATETIME    ,
	CONSTRAINT PK_DIM_DATE PRIMARY KEY ( DATE_ID )
 );

CREATE  TABLE "carcrash_dw_lgl".INSTANCE.DIM_LOCATION ( 
	LOCATION_ID          BIGINT NOT NULL   ,
	BOROUGH              VARCHAR(255)    ,
	LATITUDE             DOUBLE    ,
	LONGITUDE            DOUBLE    ,
	ZIP_CODE             INT    ,
	ON_STREET_NAME       VARCHAR(255)    ,
	OFF_STREET_NAME      VARCHAR(255)    ,
	CROSS_STREET_NAME    VARCHAR(255)    ,
	CONSTRAINT PK_DIM_LOCATION PRIMARY KEY ( LOCATION_ID )
 );

CREATE  TABLE "carcrash_dw_lgl".INSTANCE.DIM_VEHICLE_TYPE ( 
	VEHICLE_ID           BIGINT NOT NULL   ,
	VEHICLE_TYPE_CODE    VARCHAR(255)    ,
	CONSTRAINT PK_DIM_VEHICLE_TYPE PRIMARY KEY ( VEHICLE_ID )
 );

CREATE  TABLE "carcrash_dw_lgl".INSTANCE.FACTS_CRASHES ( 
	FACT_ID              BIGINT NOT NULL   ,
	NUMBER_OF_PERSONS_INJURED INT    ,
	NUMBER_OF_PERSONS_KILLED INT    ,
	NUMBER_OF_PEDESTRIANS_INJURED INT    ,
	NUMBER_OF_PEDESTRIANS_KILLED INT    ,
	NUMBER_OF_CYCLIST_INJURED INT    ,
	NUMBER_OF_CYCLIST_KILLED INT    ,
	NUMBER_OF_MOTORIST_INJURED INT    ,
	NUMBER_OF_MOTORIST_KILLED INT    ,
	NUMBER_OF_ACCIDENTS  INT    ,
	LOCATION_ID          INT    ,
	DATE_ID              BIGINT    ,
	VAHICLE_ID           INT    ,
	CONTRIBUTING_FACTOR_ID INT    ,
	CONSTRAINT PK_FACTS_CRASHES PRIMARY KEY ( FACT_ID )
 );
